CHECKERS_LITE_DIR := $(shell pwd)
CHECKERS_LITE_SOURCE=$(CHECKERS_LITE_DIR)/src
CHECKERS_LITE_INCLUDE=-I$(CHECKERS_LITE_DIR)/include
BOOST_DIST=$(CHECKERS_LITE_DIR)/boost

CXX = g++
CXXFLAGS += -std=c++0x -Wall -g -O2 -fno-strict-aliasing
BOOST_INCLUDE += -I$(BOOST_DIST)/include
LIBS = -L$(BOOST_DIST)/lib/ -lboost_thread -lboost_system -lboost_filesystem
LDFLAGS = 
COMMON_SOURCES = 
CLIENT_SOURCES = $(CHECKERS_LITE_SOURCE)/tcp_client.cpp $(CHECKERS_LITE_SOURCE)/board.cpp 
SERVER_SOURCES = $(CHECKERS_LITE_SOURCE)/tcp_server.cpp $(CHECKERS_LITE_SOURCE)/tcp_connection.cpp $(CHECKERS_LITE_SOURCE)/board.cpp $(CHECKERS_LITE_SOURCE)/moves.cpp
COMMON_OBJECTS = $(COMMON_SOURCES:%.cpp=%.o)
CLIENT_OBJECTS = $(CLIENT_SOURCES:%.cpp=%.o)
SERVER_OBJECTS = $(SERVER_SOURCES:%.cpp=%.o)
SERVER_EXECUTABLE = checkers_lite_server
CLIENT_EXECUTABLE = checkers_lite_client

.PHONY: all $(SERVER_EXECUTABLE) $(CLIENT_EXECUTABLE)

all: $(SERVER_EXECUTABLE) $(CLIENT_EXECUTABLE)

$(SERVER_EXECUTABLE): $(COMMON_OBJECTS) $(SERVER_OBJECTS)
	$(CXX)  -o $@ $(SERVER_OBJECTS) $(LDFLAGS) $(LIBS) $(ARCS) -pthread

$(CLIENT_EXECUTABLE): $(COMMON_OBJECTS) $(CLIENT_OBJECTS)
	$(CXX)  -o $@ $(CLIENT_OBJECTS) $(LDFLAGS) $(LIBS) $(ARCS) -pthread

%.o: %.cpp
	$(CXX) -o $@ $(CXXFLAGS) $(BOOST_INCLUDE) $(CHECKERS_LITE_INCLUDE) -c $<
	
clean:
	rm -rf ${SERVER_OBJECTS} ${CLIENT_OBJECTS} $(SERVER_EXECUTABLE) $(CLIENT_EXECUTABLE) 
